name: "Podcast Generator"
author: "RAM SHAM Bahaduri"
description: "Generates a feed for a podcast from file"
inputs:
  email:
    description: The committer's email address
    required: true
    default: ${{ github.actor }}#localhost
  name:
    description: The committer's name
    required: true
    default: ${{ github.actor }}
runs:
  using: "docker"
  image: "Dockerfile"
  env:
    INPUT_EMAIL: ${{ inputs.email }}
    INPUT_NAME: ${{ inputs.name }}
branding: 
  icon: "git-branch"
  color: "red"
