name: "Podcast Generator"
author: "RAM SHAM Bahaduri"
description: "GEnerates a feed for a podcast from file"
runs:
  using: "docker"
  image: "Dockerfile"
brancding: 
  icon: "git-branch"
  color: "red"
inputs:
  email:
    description: The commiter's email address
    required: true
    default: ${{ github.actor }}#localhost
  name:
    description: The committer's name
    required: true
    default: ${{ github.actor }}